### PR TITLE
Makefile improvements

### PR DESCRIPTION
**Pull request by mjtrangoni**
I made some small aesthetic changes to the [Makefile](Makefile) and fix also a `vet` warning,
```
>> formatting code
>> vetting code
lustre_exporter.go:60: range variable c captured by func literal
exit status 1
Makefile:35: recipe for target 'vet' failed
make: *** [vet] Error 1
```
In addition I create a (.gitignore)(gitignore) file to exclude ***~** and the binary created **lustre_exporter**.

I hope you agree with the changes. Thanks!

### CODE REVIEW

**Comment by joehandzik** [comment]
@mjtrangoni This all looks good to me, though your third commit (Fix range variable c...) probably makes sense as a separate PR. Can you cherry-pick it out of here and into a new branch, and spin off a second PR to cover it? Otherwise, I'll let @roclark take a look, but this looks good to me. We'll merge whenever you move your third commit to a new PR.

**Comment by mjtrangoni** [comment]
@joehandzik I made some more improvements, and drop the `Fix` change as you requested.

Curiously I am getting no error with Travis-CI, and local I am having this,
```
$ make 
>> formatting code
>> vetting code
lustre_exporter.go:60: range variable c captured by func literal
exit status 1
Makefile:34: recipe for target 'vet' failed
make: *** [vet] Error 1
```
Any ideas why it doesn't look the same?

**Comment by joehandzik** [comment]
@mjtrangoni Not sure why your result would be different, I'm trying 'go vet' against master and it's failing with the same error that you get too. If you spin off a PR to fix that issue though, I can merge it and then you can rebase the change into this PR, which should fix the problem locally too.

**Comment by mjtrangoni** [comment]
@joehandzik done. See #65

**Comment by joehandzik** [comment]
#65 merged, rebase when you have a chance and confirm that your local builds are working again!

**Comment by mjtrangoni** [comment]
It works!
```
$ make
>> formatting code
>> vetting code
>> building binaries
 >   lustre_exporter
>> running tests
?   	github.com/HewlettPackard/lustre_exporter	[no test files]
?   	github.com/HewlettPackard/lustre_exporter/sources	[no test files]
```

**Comment by joehandzik** [comment]
@mjtrangoni Awesome! I'll wait for an ack from @roclark then pull in this PR.

**Pull request merged**
