### PR TITLE
Add CHANGELOG.md

### LINKED ISSUE #55: Semantic Versioning and CHANGELOG.md
I wanted to point you out to use [semantic versioning](http://semver.org/) for versioning.

See that you have `1.00.0-rc.1` instead of `1.0.0-rc.1` in [VERSION](https://github.com/HewlettPackard/lustre_exporter/blob/master/VERSION) and `v0.01.0` instead of `v0.1.0` released.

A `CHANGELOG.md` file would be a nice to have too.

Thanks!

### PR DESCRIPTION
**Pull request by joehandzik**
Created with github-changelog-generator

Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

Fixes #55

### CODE REVIEW

**Comment by joehandzik** [comment]
I used this tool: https://github.com/skywinder/github-changelog-generator

I think the changelog is pretty good, personally. @mjtrangoni, any thoughts? Does this satisfy your goals for a CHANGELOG?

**Comment by joehandzik** [comment]
@roclark We already tagged the 0.01.0 release, so the cat's out of the bag there. It'll shift to 1.0.0 when we cut the next release, so there will only be a little bit of inconsistency if someone was using 0.01.0 (which should be a small group).

There's a little bit of sprawl, but this makes it easy to figure out what was done in each release. I took a short trip across the internet, and there are folks who think that the changelog needs to be thinned out, but I don't think this project will see as much churn in future releases as it has in these early releases. I think it'll be more useful than harmful to keep a detailed log.

**Comment by roclark** [comment]
Works for me! I think it looks good. As an aside, this is a very similar format to what the Lustre community uses for their changelog, so I think it's fitting.

Going to wait to see if @mjtrangoni makes any comments - otherwise I will pull this in.

**Comment by mjtrangoni** [comment]
Nice! I didn`t know this tool. You could maybe remove the title, which seems redundant to me. Thanks!

**Comment by joehandzik** [comment]
@mjtrangoni The title is auto-generated, so in the interest of avoiding problems when re-running the tool for every release I'm going to leave it in there (it's a little redundant, but I don't think it really causes any problems).

**Pull request merged**
