### PR TITLE
Updating to use dep instead of govendor

### PR DESCRIPTION
**Pull request by joehandzik**
…ckages.

Signed-Off-By: Joe Handzik <joseph.t.handzik@hpe.com>

### CODE REVIEW

**Comment by joehandzik** [comment]
Fixes #127. @mjtrangoni, care to take a look and make sure this is what you want? If you like what you see, I'll merge with master and tag version 1.1.0.

**Comment by roclark** [comment]
I don't have any issues with the commit itself, but the title is long, so it wraps to the description field which looks a little funky...

**Comment by mjtrangoni** [comment]
LGTM

**Comment by joehandzik** [comment]
@roclark Fixed that just now.
@mjtrangoni Thanks for taking a look! I'll merge, update the changelog, and tag in a moment.

**Pull request merged**
