### PR TITLE
Support Kingpin and improve help text

### LINKED ISSUE #119: Feature request: -collector Options
Hi,
I want to make a feature request. What about listing the flag options, like `Valid levels: [core, extended, disabled]`? I think it would be more understandable.

```
Usage of ./lustre_exporter:
  -collector.client string
        Enable Client metrics (default "extended")
[...]
  -log.level value
        Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal]
```

Thanks!

### LINKED ISSUE #120: Feature request: Switch to kingpin
Hi,

Prometheus and many exporters are switching to [kingpin](https://github.com/alecthomas/kingpin). See also [prometheus#2455](https://github.com/prometheus/prometheus/issues/2455).
Thanks!

### PR DESCRIPTION
**Pull request by joehandzik**
This PR has two commits in it. The first commit adds support for Kingpin v2 and adds it to our vendor directory. The second commit switches the collector.* flags to use the Enum capability of Kingpin, which has the added benefit of filtering out invalid options. We also list out the valid options in the default helptext (though attempting to use an invalid option will result in the valid options being pushed to stdout as well).

This fixes #119 and fixes #120

### CODE REVIEW

**Comment by mjtrangoni** [comment]
Nice work! Thanks! 
I have just one more thing I found right now. Could you sort the flags alphabetically? I am also seeing the same issue at the node_exporter. This is really strange.

**Comment by joehandzik** [comment]
@mjtrangoni I just made the ordering tweak that you requested. The gotcha here is that the help flag always comes first in the flag list, so I can't alphabetize all flags. I decided to put --help and --version together at the top of the list, (they fit together logically to me, since they don't actually result in a running exporter) and have the rest of the flags together for the rest of the list.

**Comment by mjtrangoni** [comment]
Hi @joehandzik , 

Thanks! I find the '--help-man' option really cool too! You can create a manual on the fly.

**Comment by joehandzik** [comment]
@mjtrangoni I thought it was a nice addition too. Kingpin was pretty much a drop-in replacement with some nice extra features, so thanks for motivating me to get it into our exporter.

**Pull request merged**
